http:
  middlewares:
      s1:
        headers:
          accessControlAllowMethods:
            - GET
            - OPTIONS
            - PUT
            - POST
          accessControlAllowOriginList:
            - *
          accessControlMaxAge: 100
          addVaryHeader: true
  routers:
    r1:
      rule: "!Host(`google.com`)"
      service: s1
  services:
    s1:
      loadBalancer:
        passHostHeader: false
        servers:
  
